INSERT INTO roles (id,name) VALUES (1,'ADMIN'),(2,'MANAGER'),(3,'TECHNICIAN');
INSERT INTO permissions (id,code,description) VALUES
(1,'user:create','user create'),
(2,'user:read','user read'),
(3,'user:update','user update'),
(4,'asset:create','asset create'),
(5,'asset:read','asset read'),
(6,'asset:update','asset update'),
(7,'asset:delete','asset delete'),
(8,'work_order:create','work_order create'),
(9,'work_order:read','work_order read'),
(10,'work_order:update','work_order update'),
(11,'work_order:assign','work_order assign'),
(12,'work_order:status:update','work_order status update'),
(13,'work_order:cancel','work_order cancel'),
(14,'audit:read','audit read');
INSERT INTO role_permissions (role_id,permission_id) VALUES
(1,1),
(1,2),
(1,3),
(1,4),
(1,5),
(1,6),
(1,7),
(1,8),
(1,9),
(1,10),
(1,11),
(1,12),
(1,13),
(1,14),
(2,2),
(2,4),
(2,5),
(2,6),
(2,8),
(2,9),
(2,10),
(2,11),
(2,12),
(2,13),
(2,14),
(3,5),
(3,9),
(3,12);
