// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assetHasOpenOrders = `-- name: AssetHasOpenOrders :one
SELECT EXISTS(SELECT 1 FROM work_orders WHERE asset_id=$1 AND status IN ('OPEN','ASSIGNED','IN_PROGRESS'))
`

func (q *Queries) AssetHasOpenOrders(ctx context.Context, assetID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, assetHasOpenOrders, assetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const assetHasOrders = `-- name: AssetHasOrders :one
SELECT EXISTS(SELECT 1 FROM work_orders WHERE asset_id=$1)
`

func (q *Queries) AssetHasOrders(ctx context.Context, assetID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, assetHasOrders, assetID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const assetVisibleTo = `-- name: AssetVisibleTo :one
SELECT EXISTS(SELECT 1 FROM work_orders WHERE asset_id=$1 AND assigned_to=$2)
`

type AssetVisibleToParams struct {
	AssetID    pgtype.UUID
	AssignedTo pgtype.UUID
}

func (q *Queries) AssetVisibleTo(ctx context.Context, arg AssetVisibleToParams) (bool, error) {
	row := q.db.QueryRow(ctx, assetVisibleTo, arg.AssetID, arg.AssignedTo)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countAssets = `-- name: CountAssets :one
SELECT count(*) FROM assets a
WHERE ($1::text='' OR a.status=$1::text)
AND ($2::text='' OR a.category=$2::text)
AND ($3::text='' OR a.name ILIKE $3::text OR a.asset_code ILIKE $3::text OR a.location ILIKE $3::text)
AND (NOT $4::boolean OR EXISTS(SELECT 1 FROM work_orders w WHERE w.asset_id=a.id AND w.assigned_to=$5::uuid))
`

type CountAssetsParams struct {
	StatusFilter   string
	CategoryFilter string
	SearchPattern  string
	Scoped         bool
	ActorID        pgtype.UUID
}

func (q *Queries) CountAssets(ctx context.Context, arg CountAssetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAssets,
		arg.StatusFilter,
		arg.CategoryFilter,
		arg.SearchPattern,
		arg.Scoped,
		arg.ActorID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets WHERE id=$1
`

func (q *Queries) DeleteAsset(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAsset, id)
	return err
}

const getAsset = `-- name: GetAsset :one
SELECT id, asset_code, name, category, location, status, created_at, updated_at FROM assets WHERE id=$1
`

func (q *Queries) GetAsset(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AssetCode,
		&i.Name,
		&i.Category,
		&i.Location,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAsset = `-- name: InsertAsset :one
INSERT INTO assets(asset_code,name,category,location,status) VALUES($1,$2,$3,$4,$5) RETURNING id, asset_code, name, category, location, status, created_at, updated_at
`

type InsertAssetParams struct {
	AssetCode string
	Name      string
	Category  string
	Location  string
	Status    string
}

func (q *Queries) InsertAsset(ctx context.Context, arg InsertAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, insertAsset,
		arg.AssetCode,
		arg.Name,
		arg.Category,
		arg.Location,
		arg.Status,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AssetCode,
		&i.Name,
		&i.Category,
		&i.Location,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAssets = `-- name: ListAssets :many
SELECT a.id, a.asset_code, a.name, a.category, a.location, a.status, a.created_at, a.updated_at FROM assets a
WHERE ($1::text='' OR a.status=$1::text)
AND ($2::text='' OR a.category=$2::text)
AND ($3::text='' OR a.name ILIKE $3::text OR a.asset_code ILIKE $3::text OR a.location ILIKE $3::text)
AND (NOT $4::boolean OR EXISTS(SELECT 1 FROM work_orders w WHERE w.asset_id=a.id AND w.assigned_to=$5::uuid))
ORDER BY a.created_at DESC,a.id DESC LIMIT $7::int OFFSET $6::int
`

type ListAssetsParams struct {
	StatusFilter   string
	CategoryFilter string
	SearchPattern  string
	Scoped         bool
	ActorID        pgtype.UUID
	PageOffset     int32
	PageLimit      int32
}

func (q *Queries) ListAssets(ctx context.Context, arg ListAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssets,
		arg.StatusFilter,
		arg.CategoryFilter,
		arg.SearchPattern,
		arg.Scoped,
		arg.ActorID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.AssetCode,
			&i.Name,
			&i.Category,
			&i.Location,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAsset = `-- name: LockAsset :one
SELECT id, asset_code, name, category, location, status, created_at, updated_at FROM assets WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockAsset(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, lockAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AssetCode,
		&i.Name,
		&i.Category,
		&i.Location,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets SET name=$2,category=$3,location=$4,status=$5,updated_at=clock_timestamp() WHERE id=$1 RETURNING id, asset_code, name, category, location, status, created_at, updated_at
`

type UpdateAssetParams struct {
	ID       pgtype.UUID
	Name     string
	Category string
	Location string
	Status   string
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.ID,
		arg.Name,
		arg.Category,
		arg.Location,
		arg.Status,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AssetCode,
		&i.Name,
		&i.Category,
		&i.Location,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
