// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_logs (actor_id,action,entity_type,entity_id,old_value,new_value,request_id)
VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type InsertAuditParams struct {
	ActorID    pgtype.UUID
	Action     string
	EntityType string
	EntityID   pgtype.UUID
	OldValue   []byte
	NewValue   []byte
	RequestID  string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.OldValue,
		arg.NewValue,
		arg.RequestID,
	)
	return err
}
