// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditLogs = `-- name: CountAuditLogs :one
SELECT count(*) FROM audit_logs
WHERE ($1::uuid IS NULL OR actor_id=$1::uuid)
AND ($2::text='' OR action=$2::text)
AND ($3::text='' OR entity_type=$3::text)
AND ($4::uuid IS NULL OR entity_id=$4::uuid)
`

type CountAuditLogsParams struct {
	ActorFilter  pgtype.UUID
	ActionFilter string
	TypeFilter   string
	EntityFilter pgtype.UUID
}

func (q *Queries) CountAuditLogs(ctx context.Context, arg CountAuditLogsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditLogs,
		arg.ActorFilter,
		arg.ActionFilter,
		arg.TypeFilter,
		arg.EntityFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAudit = `-- name: InsertAudit :exec
INSERT INTO audit_logs (actor_id,action,entity_type,entity_id,old_value,new_value,request_id)
VALUES ($1,$2,$3,$4,$5,$6,$7)
`

type InsertAuditParams struct {
	ActorID    pgtype.UUID
	Action     string
	EntityType string
	EntityID   pgtype.UUID
	OldValue   []byte
	NewValue   []byte
	RequestID  string
}

func (q *Queries) InsertAudit(ctx context.Context, arg InsertAuditParams) error {
	_, err := q.db.Exec(ctx, insertAudit,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.OldValue,
		arg.NewValue,
		arg.RequestID,
	)
	return err
}

const insertUserUpdateAudit = `-- name: InsertUserUpdateAudit :exec
INSERT INTO audit_logs(actor_id,action,entity_type,entity_id,old_value,new_value,request_id)
VALUES($1,'USER_UPDATED','user',$2,$3,$4,$5)
`

type InsertUserUpdateAuditParams struct {
	ActorID   pgtype.UUID
	EntityID  pgtype.UUID
	OldValue  []byte
	NewValue  []byte
	RequestID string
}

func (q *Queries) InsertUserUpdateAudit(ctx context.Context, arg InsertUserUpdateAuditParams) error {
	_, err := q.db.Exec(ctx, insertUserUpdateAudit,
		arg.ActorID,
		arg.EntityID,
		arg.OldValue,
		arg.NewValue,
		arg.RequestID,
	)
	return err
}

const listAuditLogs = `-- name: ListAuditLogs :many
SELECT id, actor_id, action, entity_type, entity_id, old_value, new_value, request_id, created_at FROM audit_logs
WHERE ($1::uuid IS NULL OR actor_id=$1::uuid)
AND ($2::text='' OR action=$2::text)
AND ($3::text='' OR entity_type=$3::text)
AND ($4::uuid IS NULL OR entity_id=$4::uuid)
ORDER BY created_at DESC,id DESC LIMIT $6::int OFFSET $5::int
`

type ListAuditLogsParams struct {
	ActorFilter  pgtype.UUID
	ActionFilter string
	TypeFilter   string
	EntityFilter pgtype.UUID
	PageOffset   int32
	PageLimit    int32
}

func (q *Queries) ListAuditLogs(ctx context.Context, arg ListAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogs,
		arg.ActorFilter,
		arg.ActionFilter,
		arg.TypeFilter,
		arg.EntityFilter,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.OldValue,
			&i.NewValue,
			&i.RequestID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
