// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Asset struct {
	ID        pgtype.UUID
	AssetCode string
	Name      string
	Category  string
	Location  string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AuditLog struct {
	ID         pgtype.UUID
	ActorID    pgtype.UUID
	Action     string
	EntityType string
	EntityID   pgtype.UUID
	OldValue   []byte
	NewValue   []byte
	RequestID  string
	CreatedAt  pgtype.Timestamptz
}

type Permission struct {
	ID          int16
	Code        string
	Description string
}

type Role struct {
	ID   int16
	Name string
}

type RolePermission struct {
	RoleID       int16
	PermissionID int16
}

type User struct {
	ID           pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
	RoleID       int16
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type WorkOrder struct {
	ID              pgtype.UUID
	WorkOrderNumber string
	AssetID         pgtype.UUID
	Title           string
	Description     string
	Priority        string
	Status          string
	CreatedBy       pgtype.UUID
	AssignedTo      pgtype.UUID
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
}
