// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCurrentUser = `-- name: GetCurrentUser :one
SELECT u.id, u.name, u.email, u.password_hash, u.role_id, u.is_active, u.created_at, u.updated_at, r.name AS role FROM users u JOIN roles r ON r.id=u.role_id WHERE u.id=$1
`

type GetCurrentUserRow struct {
	ID           pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
	RoleID       int16
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Role         string
}

func (q *Queries) GetCurrentUser(ctx context.Context, id pgtype.UUID) (GetCurrentUserRow, error) {
	row := q.db.QueryRow(ctx, getCurrentUser, id)
	var i GetCurrentUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const getLoginUser = `-- name: GetLoginUser :one
SELECT u.id, u.name, u.email, u.password_hash, u.role_id, u.is_active, u.created_at, u.updated_at, r.name AS role FROM users u JOIN roles r ON r.id=u.role_id WHERE u.email=$1
`

type GetLoginUserRow struct {
	ID           pgtype.UUID
	Name         string
	Email        string
	PasswordHash string
	RoleID       int16
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	Role         string
}

func (q *Queries) GetLoginUser(ctx context.Context, email string) (GetLoginUserRow, error) {
	row := q.db.QueryRow(ctx, getLoginUser, email)
	var i GetLoginUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const hasAdministrator = `-- name: HasAdministrator :one
SELECT EXISTS(SELECT 1 FROM users u JOIN roles r ON r.id=u.role_id WHERE r.name='ADMIN')
`

func (q *Queries) HasAdministrator(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, hasAdministrator)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (name,email,password_hash,role_id)
VALUES ($1,$2,$3,(SELECT id FROM roles WHERE name=$4::text)) RETURNING id, name, email, password_hash, role_id, is_active, created_at, updated_at
`

type InsertUserParams struct {
	Name         string
	Email        string
	PasswordHash string
	Role         string
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockUserAdministration = `-- name: LockUserAdministration :exec
SELECT pg_advisory_xact_lock(716493001)
`

func (q *Queries) LockUserAdministration(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockUserAdministration)
	return err
}
