// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: work_orders.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countWorkOrders = `-- name: CountWorkOrders :one
SELECT count(*) FROM work_orders w
WHERE ($1::text='' OR w.status=$1::text)
AND ($2::text='' OR w.priority=$2::text)
AND ($3::uuid IS NULL OR w.asset_id=$3::uuid)
AND ($4::uuid IS NULL OR w.assigned_to=$4::uuid)
AND (NOT $5::boolean OR w.assigned_to=$6::uuid)
`

type CountWorkOrdersParams struct {
	StatusFilter   string
	PriorityFilter string
	AssetFilter    pgtype.UUID
	AssigneeFilter pgtype.UUID
	Scoped         bool
	ActorID        pgtype.UUID
}

func (q *Queries) CountWorkOrders(ctx context.Context, arg CountWorkOrdersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkOrders,
		arg.StatusFilter,
		arg.PriorityFilter,
		arg.AssetFilter,
		arg.AssigneeFilter,
		arg.Scoped,
		arg.ActorID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWorkOrder = `-- name: GetWorkOrder :one
SELECT id, work_order_number, asset_id, title, description, priority, status, created_by, assigned_to, created_at, updated_at, completed_at FROM work_orders WHERE id=$1
`

func (q *Queries) GetWorkOrder(ctx context.Context, id pgtype.UUID) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, getWorkOrder, id)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.WorkOrderNumber,
		&i.AssetID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertWorkOrder = `-- name: InsertWorkOrder :one
INSERT INTO work_orders(work_order_number,asset_id,title,description,priority,created_by)
VALUES ((SELECT 'WO-'||to_char(clock_timestamp() AT TIME ZONE 'UTC','YYYY')||'-'||lpad(n::text,greatest(6,length(n::text)),'0') FROM (SELECT nextval('work_order_number_seq') AS n) seq),$1,$2,$3,$4,$5) RETURNING id, work_order_number, asset_id, title, description, priority, status, created_by, assigned_to, created_at, updated_at, completed_at
`

type InsertWorkOrderParams struct {
	AssetID     pgtype.UUID
	Title       string
	Description string
	Priority    string
	CreatedBy   pgtype.UUID
}

func (q *Queries) InsertWorkOrder(ctx context.Context, arg InsertWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, insertWorkOrder,
		arg.AssetID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.CreatedBy,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.WorkOrderNumber,
		&i.AssetID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listWorkOrders = `-- name: ListWorkOrders :many
SELECT w.id, w.work_order_number, w.asset_id, w.title, w.description, w.priority, w.status, w.created_by, w.assigned_to, w.created_at, w.updated_at, w.completed_at FROM work_orders w
WHERE ($1::text='' OR w.status=$1::text)
AND ($2::text='' OR w.priority=$2::text)
AND ($3::uuid IS NULL OR w.asset_id=$3::uuid)
AND ($4::uuid IS NULL OR w.assigned_to=$4::uuid)
AND (NOT $5::boolean OR w.assigned_to=$6::uuid)
ORDER BY w.created_at DESC,w.id DESC LIMIT $8::int OFFSET $7::int
`

type ListWorkOrdersParams struct {
	StatusFilter   string
	PriorityFilter string
	AssetFilter    pgtype.UUID
	AssigneeFilter pgtype.UUID
	Scoped         bool
	ActorID        pgtype.UUID
	PageOffset     int32
	PageLimit      int32
}

func (q *Queries) ListWorkOrders(ctx context.Context, arg ListWorkOrdersParams) ([]WorkOrder, error) {
	rows, err := q.db.Query(ctx, listWorkOrders,
		arg.StatusFilter,
		arg.PriorityFilter,
		arg.AssetFilter,
		arg.AssigneeFilter,
		arg.Scoped,
		arg.ActorID,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkOrder{}
	for rows.Next() {
		var i WorkOrder
		if err := rows.Scan(
			&i.ID,
			&i.WorkOrderNumber,
			&i.AssetID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.Status,
			&i.CreatedBy,
			&i.AssignedTo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkOrder = `-- name: LockWorkOrder :one
SELECT id, work_order_number, asset_id, title, description, priority, status, created_by, assigned_to, created_at, updated_at, completed_at FROM work_orders WHERE id=$1 FOR UPDATE
`

func (q *Queries) LockWorkOrder(ctx context.Context, id pgtype.UUID) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, lockWorkOrder, id)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.WorkOrderNumber,
		&i.AssetID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const shareAsset = `-- name: ShareAsset :one
SELECT id, asset_code, name, category, location, status, created_at, updated_at FROM assets WHERE id=$1 FOR SHARE
`

func (q *Queries) ShareAsset(ctx context.Context, id pgtype.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, shareAsset, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.AssetCode,
		&i.Name,
		&i.Category,
		&i.Location,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const shareUser = `-- name: ShareUser :one
SELECT id, name, email, password_hash, role_id, is_active, created_at, updated_at FROM users WHERE id=$1 FOR SHARE
`

func (q *Queries) ShareUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, shareUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.RoleID,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkOrder = `-- name: UpdateWorkOrder :one
UPDATE work_orders SET title=$1,description=$2,priority=$3,status=$4,assigned_to=$5,
completed_at=CASE WHEN $4::text='COMPLETED' THEN clock_timestamp() ELSE NULL END,updated_at=clock_timestamp()
WHERE id=$6 RETURNING id, work_order_number, asset_id, title, description, priority, status, created_by, assigned_to, created_at, updated_at, completed_at
`

type UpdateWorkOrderParams struct {
	Title       string
	Description string
	Priority    string
	Status      string
	AssignedTo  pgtype.UUID
	ID          pgtype.UUID
}

func (q *Queries) UpdateWorkOrder(ctx context.Context, arg UpdateWorkOrderParams) (WorkOrder, error) {
	row := q.db.QueryRow(ctx, updateWorkOrder,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Status,
		arg.AssignedTo,
		arg.ID,
	)
	var i WorkOrder
	err := row.Scan(
		&i.ID,
		&i.WorkOrderNumber,
		&i.AssetID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.Status,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
